### ISSUE TITLE
Buffer modification state doesn't change after saving

### ISSUE THREAD

**Issue by seh** [Fanael/persistent-scratch#31]
When I have `persistent-scratch-mode` enabled in my _\*scratch\*_ buffer and I press the <kbd>C-x</kbd> <kbd>C-s</kbd> sequence, the `persistent-scratch-save` function runs and reports in the minibuffer that my buffer's content was saved to a particular file. However, the askterisk in the modeline indicating that the buffer has been modified since it was last saved remains active, and the `buffer-modified-p` function continues to return `t`.

Is it possible to clear the modified state of the _\*scratch\*_ buffer after the `persistent-scratch-save` function? Perhaps we can call [`(set-buffer-modified-p nil)`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer-Modification.html) or `(not-modified)`.

**Comment by notetiene** [comment]
Well, it's funny you made this issue.  I've been annoyed by this behaviour for years.  I then decided to look at issues about that and I see this one (3 days ago).

I made a fork in order to implement this feature, however it looks this mode doesn't just save and restore the file.  It can also save:
> - `major-mode`: save the major mode.
> - `point`: save the positions of `point` and `mark`.
> - `narrowing`: save the region the buffer is narrowed to.
> - `text-properties`: save the text properties of the buffer contents."

How can someone tracking those things be sure it will be saved?  We would need use the `post-command-hook` (which runs every time a command is run) and filters the candidates.  I'm not sure it can be done easily.

**Comment by seh** [comment]
Trapping completion of [the `persistent-scratch-save` function](https://github.com/Fanael/persistent-scratch/blob/92f540e7d310ec2e0b636eff1033cf78f0d9eb40/persistent-scratch.el#L156-L181) would include all of that information along with the buffer content.

**Comment by notetiene** [comment]
Oops, sorry. I forgot to say I made a patch #33

**Comment by Fanael** [comment]
It's *amazing* that I forgot about this basic thing for so long.

Fixed by #33, thanks!
